import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import { copy } from 'esbuild-plugin-copy';
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = (process.argv[2] === 'production');

// Optional local convenience: load OBSIDIAN_REST_URL/OBSIDIAN_REST_API_KEY
// from a gitignored .env file at the repo root, if present, without
// overriding any already-set environment variables or adding a dotenv
// dependency. See reloadObsidian() below and CONTRIBUTING.md.
function loadDotEnv() {
	const envPath = path.resolve(process.cwd(), ".env");
	if (!fs.existsSync(envPath))
		return;
	for (const line of fs.readFileSync(envPath, "utf8").split("\n")) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith("#"))
			continue;
		const eq = trimmed.indexOf("=");
		if (eq === -1)
			continue;
		const key = trimmed.slice(0, eq).trim();
		const value = trimmed.slice(eq + 1).trim();
		if (!(key in process.env))
			process.env[key] = value;
	}
}

// Personal dev-loop convenience, not required to build this plugin: if
// OBSIDIAN_REST_API_KEY is configured, tells a locally running Obsidian (via
// the Local REST API community plugin) to reload itself after a production
// build, so the freshly built main.js actually takes effect - Obsidian
// doesn't hot-reload a plugin's code just because the file on disk changed,
// it keeps running whatever was already loaded in memory. Silently does
// nothing if the key isn't set, and never fails the build if the request
// errors (e.g. Obsidian isn't running right now) - this is a nice-to-have,
// not a build requirement, and deliberately never hardcodes the API key
// here since this file is committed to the (public) repo.
async function reloadObsidian() {
	loadDotEnv();
	const apiKey = process.env.OBSIDIAN_REST_API_KEY;
	if (!apiKey)
		return;
	const baseUrl = process.env.OBSIDIAN_REST_URL ?? "http://127.0.0.1:27123";
	try {
		const controller = new AbortController();
		const timeout = setTimeout(() => controller.abort(), 3000);
		const res = await fetch(`${baseUrl}/commands/app%3Areload`, {
			method: "POST",
			headers: { Authorization: `Bearer ${apiKey}` },
			signal: controller.signal,
		});
		clearTimeout(timeout);
		console.log(res.ok ? "Reloaded Obsidian." : `Obsidian reload request returned HTTP ${res.status}.`);
	} catch (e) {
		console.log(`Skipped Obsidian reload (${e.message}).`);
	}
}

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/closebrackets',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/comment',
		'@codemirror/fold',
		'@codemirror/gutter',
		'@codemirror/highlight',
		'@codemirror/history',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/matchbrackets',
		'@codemirror/panel',
		'@codemirror/rangeset',
		'@codemirror/rectangular-selection',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/stream-parser',
		'@codemirror/text',
		'@codemirror/tooltip',
		'@codemirror/view',
		...builtins
	],
	plugins: [
		copy({
			assets: [{
				from: ["./manifest.json", "./main.js", "./styles.css"],
				to: ["./test-vault/.obsidian/plugins/time-tracker/."]
			}]
		}),
	],
	format: 'cjs',
	watch: !prod,
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
}).then(async () => {
	// Only after a one-shot production build, not `dev`'s continuous watch
	// rebuilds - reloading Obsidian on every keystroke-triggered rebuild
	// would be disruptive rather than helpful.
	if (prod)
		await reloadObsidian();
}).catch(() => process.exit(1));
